export const Addons = [
  {
    command: "toggle",
    title: "Toggle Default/MarkPen Editors",
    icon: "$(multiple-windows)",
    text: "Toggle",
    keybinding: "ctrl+alt+e",
  },
  {
    command: "pasteimage",
    title: "Paste image from clipboard",
    icon: "$(paste)",
    text: "Paste Image",
    keybinding: "ctrl+alt+v",
    contextKey: "clipboardHasImage",
    vscWebviewContext: true,
  },
  {
    command: "cut",
    title: "Cut",
    icon: "$(scissors)",
    text: "Cut",
    keybinding: "ctrl+x",
    contextKey: "vditorHasSelection",
    vscWebviewContext: true,
  },
  {
    command: "paste",
    title: "Paste",
    icon: "$(paste)",
    text: "Paste",
    keybinding: "ctrl+v",
    contextKey: "vditorHasClipboard",
    vscWebviewContext: true,
  },
  {
    command: "findInFiles",
    title: "Find in Current File",
    icon: "$(find)",
    text: "Find",
    keybinding: "ctrl+alt+f",
  },
  {
    command: "replaceInFiles",
    title: "Replace in Current File",
    icon: "$(find-and-replace)",
    text: "Replace",
    keybinding: "ctrl+h",
  },
  {
    command: "openKeyboardShortcuts",
    title: "Open MarkPen Keyboard Shortcuts",
    icon: "$(keyboard)",
    text: "Keyboard Shortcuts",
  },
];
