export const Addons = [
  {
    command: "toggle",
    title: "Toggle Editor",
    icon: "$(multiple-windows)",
    text: "Toggle",
    keybinding: "ctrl+alt+e",
  },
  {
    command: "cycleHeading",
    title: "Cycle H1-H6 & Paragraph",
    category: "Format",
    icon: "$(symbol-number)",
    text: " H1-H6 / Paragraph",
    keybinding: "ctrl+alt+h",
  },
  {
    command: "pasteimage",
    title: "Paste Image",
    icon: "$(copy)",
    text: "Paste Image",
    keybinding: "ctrl+alt+v",
    contextKey: "clipboardHasImage",
    vscWebviewContext: true,
  },
  {
    command: "cut",
    title: "Cut",
    icon: "$(edit)",
    text: "Cut",
    keybinding: "ctrl+x",
    contextKey: "vditorHasSelection",
    vscWebviewContext: true,
  },
  {
    command: "paste",
    title: "Paste",
    icon: "$(inbox)",
    text: "Paste",
    keybinding: "ctrl+v",
    contextKey: "vditorHasClipboard",
    vscWebviewContext: true,
  },
  {
    command: "findInFiles",
    title: "Find",
    icon: "$(search)",
    text: "Find",
    keybinding: "ctrl+alt+f",
  },
  {
    command: "replaceInFiles",
    title: "Replace",
    icon: "$(replace)",
    text: "Replace",
    keybinding: "ctrl+h",
  },
  {
    command: "openKeyboardShortcuts",
    title: "MarkPen Hotkeys",
    icon: "$(keyboard)",
    text: "Keyboard Shortcuts",
  },
];
