export const Features = [
  // Heading
  {
    command: "h0",
    title: "Remove Heading",
    icon: "H0",
    text: "H0",
    keybinding: "ctrl+h",
    category: "Heading",
    selector: "h1",
    contextKey: "webviewSection",
    vscWebviewContext: "h1",
    contextGroup: "2_section_ops@4",
    keyEvent: {
      key: "h",
      code: "KeyH",
      ctrlKey: true,
      shiftKey: false,
      altKey: false,
      bubbles: true,
      cancelable: true,
    },
  },
  {
    command: "h1",
    title: "H1 Style Heading",
    icon: "H1",
    text: "H1",
    keybinding: "ctrl+alt+1",
    category: "Heading",
    selector: "h1",
    contextKey: "webviewSection",
    vscWebviewContext: "h1",
    contextGroup: "2_section_ops@4",
    keyEvent: {
      key: "1",
      code: "Digit1",
      ctrlKey: true,
      shiftKey: false,
      altKey: true,
      bubbles: true,
      cancelable: true,
    },
  },
  {
    command: "h2",
    title: "H2 Style Heading",
    icon: "H2",
    text: "H2",
    keybinding: "ctrl+alt+2",
    category: "Heading",
    selector: "h2",
    contextKey: "webviewSection",
    vscWebviewContext: "h2",
    contextGroup: "2_section_ops@4",
    keyEvent: {
      key: "2",
      code: "Digit2",
      ctrlKey: true,
      shiftKey: false,
      altKey: true,
      bubbles: true,
      cancelable: true,
    },
  },
  {
    command: "h3",
    title: "H3 Style Heading",
    icon: "H3",
    text: "H3",
    keybinding: "ctrl+alt+3",
    category: "Heading",
    selector: "h3",
    contextKey: "webviewSection",
    vscWebviewContext: "h3",
    contextGroup: "2_section_ops@4",
    keyEvent: {
      key: "3",
      code: "Digit3",
      ctrlKey: true,
      shiftKey: false,
      altKey: true,
      bubbles: true,
      cancelable: true,
    },
  },
  {
    command: "h4",
    title: "H4 Style Heading",
    icon: "H4",
    text: "H4",
    keybinding: "ctrl+alt+4",
    category: "Heading",
    selector: "h4",
    contextKey: "webviewSection",
    vscWebviewContext: "h4",
    contextGroup: "2_section_ops@4",
    keyEvent: {
      key: "4",
      code: "Digit4",
      ctrlKey: true,
      altKey: true,
      shiftKey: false,
      bubbles: true,
      cancelable: true,
    },
  },
  {
    command: "h5",
    title: "H5 Style Heading",
    icon: "H5",
    text: "H5",
    keybinding: "ctrl+alt+5",
    category: "Heading",
    selector: "h5",
    contextKey: "webviewSection",
    vscWebviewContext: "h5",
    contextGroup: "2_section_ops@4",
    keyEvent: {
      key: "5",
      code: "Digit5",
      ctrlKey: true,
      altKey: true,
      shiftKey: false,
      bubbles: true,
      cancelable: true,
    },
  },
  {
    command: "h6",
    title: "H6 Style Heading",
    icon: "H6",
    text: "H6",
    keybinding: "ctrl+alt+6",
    category: "Heading",
    selector: "h6",
    contextKey: "webviewSection",
    vscWebviewContext: "h6",
    contextGroup: "2_section_ops@4",
    keyEvent: {
      key: "6",
      code: "Digit6",
      ctrlKey: true,
      altKey: true,
      shiftKey: false,
      bubbles: true,
      cancelable: true,
    },
  },
  {
    command: "h+",
    title: "Heading Level +1",
    icon: "$(diff-added)",
    text: "H+",
    keybinding: "ctrl+=",
    category: "Heading",
    contextGroup: "1_item_ops@4",
    keyEvent: {
      key: "=",
      code: "Equal",
      ctrlKey: true,
      bubbles: true,
      cancelable: true,
    },
  },
  {
    command: "h-",
    title: "Heading Level - 1",
    icon: "$(diff-removed)",
    text: "H-",
    keybinding: "ctrl+-",
    category: "Heading",
    contextGroup: "1_item_ops@4",
    keyEvent: {
      key: "-",
      code: "Minus",
      ctrlKey: true,
      bubbles: true,
      cancelable: true,
    },
  },
  // Format
  {
    command: "bold",
    title: "Bold",
    icon: "$(bold)",
    text: "Bold",
    keybinding: "ctrl+b",
    category: "Format",
    contextGroup: "3_global_ops@1",
    keyEvent: {
      key: "b",
      code: "KeyB",
      ctrlKey: true,
      altKey: false,
      shiftKey: false,
      bubbles: true,
      cancelable: true,
    },
  },
  {
    command: "italic",
    title: "Italic",
    icon: "$(italic)",
    text: "Italic",
    keybinding: "ctrl+i",
    category: "Format",
    contextGroup: "3_global_ops@1",
    keyEvent: {
      key: "i",
      code: "KeyI",
      ctrlKey: true,
      altKey: false,
      shiftKey: false,
      bubbles: true,
      cancelable: true,
    },
  },
  {
    command: "strikethrough",
    title: "Strike",
    icon: "$(strikethrough)",
    text: "Strike",
    keybinding: "ctrl+d",
    category: "Format",
    contextGroup: "3_global_ops@1",
    keyEvent: {
      key: "d",
      code: "KeyD",
      ctrlKey: true,
      altKey: false,
      shiftKey: false,
      bubbles: true,
      cancelable: true,
    },
  },
  {
    command: "link",
    title: "Link",
    icon: "$(link)",
    text: "Link",
    keybinding: "ctrl+k",
    category: "Format",
    selector: "a",
    contextKey: "webviewItemElement",
    vscWebviewContext: "link",
    contextGroup: "1_item_ops@5",
    keyEvent: {
      key: "k",
      code: "KeyK",
      ctrlKey: true,
      altKey: false,
      shiftKey: false,
      bubbles: true,
      cancelable: true,
    },
  },
  {
    command: "inlinecode",
    title: "Monospace",
    icon: "$(symbol-string)",
    text: "Quote",
    keybinding: "ctrl+g",
    category: "Format",
    contextGroup: "3_global_ops@1",
    keyEvent: {
      key: "g",
      code: "KeyG",
      ctrlKey: true,
      altKey: false,
      shiftKey: false,
      bubbles: true,
      cancelable: true,
    },
  },
  {
    command: "unordered",
    title: "Unordered List",
    icon: "$(list-unordered)",
    text: "UL",
    keybinding: "ctrl+l",
    category: "Format",
    selector: "ul",
    contextKey: "webviewSection",
    vscWebviewContext: "unordered",
    contextGroup: "3_global_ops@1",
    keyEvent: {
      key: "l",
      code: "KeyL",
      ctrlKey: true,
      altKey: false,
      shiftKey: false,
      bubbles: true,
      cancelable: true,
    },
  },
  {
    command: "ordered",
    title: "Ordered List",
    icon: "$(list-ordered)",
    text: "OL",
    keybinding: "ctrl+o",
    category: "Format",
    selector: "ol",
    contextKey: "webviewSection",
    vscWebviewContext: "ordered",
    contextGroup: "2_section_ops@1",
    keyEvent: {
      key: "o",
      code: "KeyO",
      ctrlKey: true,
      altKey: false,
      shiftKey: false,
      bubbles: true,
      cancelable: true,
    },
  },
  {
    command: "checked",
    title: "Checked List",
    icon: "$(tasklist)",
    text: "Checked",
    keybinding: "ctrl+j",
    category: "Format",
    selector: "ul",
    contextKey: "webviewItemElement",
    vscWebviewContext: "list-item",
    contextGroup: "1_item_ops@1",
    keyEvent: {
      key: "j",
      code: "KeyJ",
      ctrlKey: true,
      altKey: false,
      shiftKey: false,
      bubbles: true,
      cancelable: true,
    },
  },
  // List
  {
    command: "checked-toggle",
    title: "Toggle Tick",
    icon: "$(check)",
    keybinding: "ctrl+shift+j",
    category: "List",
    selector: "li.vditor-task",
    contextKey: "webviewItemElement",
    vscWebviewContext: "list-item",
    contextGroup: "1_item_ops@1",
    keyEvent: {
      key: "j",
      code: "KeyJ",
      ctrlKey: true,
      shiftKey: true,
      bubbles: true,
      cancelable: true,
    },
  },
  {
    command: "indent",
    title: "(L) Indent",
    icon: "$(indent)",
    keybinding: "ctrl+shift+i",
    category: "List",
    selector: "li",
    contextKey: "webviewItemElement",
    vscWebviewContext: "list-item",
    contextGroup: "1_item_ops@1",
    keyEvent: {
      key: "i",
      code: "KeyI",
      ctrlKey: true,
      shiftKey: true,
      bubbles: true,
      cancelable: true,
    },
  },
  {
    command: "unindent",
    title: "(R) Indent",
    icon: "$(newline)",
    keybinding: "ctrl+shift+o",
    category: "List",
    selector: "li",
    contextKey: "webviewItemElement",
    vscWebviewContext: "list-item",
    contextGroup: "1_item_ops@1",
    keyEvent: {
      key: "o",
      code: "KeyO",
      ctrlKey: true,
      shiftKey: true,
      bubbles: true,
      cancelable: true,
    },
  },
  // Block Elements
  {
    command: "new-start",
    title: "Para (before)",
    icon: "$(arrow-up)",
    keybinding: "ctrl+shift+b",
    category: "Insert",
    contextGroup: "2_section_ops@4",
    keyEvent: {
      key: "b",
      code: "KeyB",
      ctrlKey: true,
      shiftKey: true,
      bubbles: true,
      cancelable: true,
    },
  },
  {
    command: "new-end",
    title: "Para (after)",
    icon: "$(arrow-down)",
    keybinding: "ctrl+shift+e",
    category: "Insert",
    contextGroup: "2_section_ops@4",
    keyEvent: {
      key: "e",
      code: "KeyE",
      ctrlKey: true,
      shiftKey: true,
      bubbles: true,
      cancelable: true,
    },
  },
  // {
  //   command: "move-up",
  //   title: "Move Block Up",
  //   icon: "$(arrow-circle-up)",
  //   keybinding: "ctrl+shift+u",
  //   category: "Blocks",
  //   contextGroup: "2_section_ops@4",
  //   keyEvent: {
  //     key: "u",
  //     code: "KeyU",
  //     ctrlKey: true,
  //     shiftKey: true,
  //     bubbles: true,
  //     cancelable: true,
  //   },
  // },
  // {
  //   command: "move-down",
  //   title: "Move Block Down",
  //   icon: "$(arrow-circle-up)",
  //   keybinding: "ctrl+shift+d",
  //   category: "Blocks",
  //   contextGroup: "2_section_ops@4",
  //   keyEvent: {
  //     key: "d",
  //     code: "KeyD",
  //     ctrlKey: true,
  //     shiftKey: true,
  //     bubbles: true,
  //     cancelable: true,
  //   },
  // },
  // {
  //   command: "remove",
  //   title: "Remove Block",
  //   icon: "$(trash)",
  //   keybinding: "ctrl+shift+x",
  //   category: "Blocks",
  //   contextGroup: "2_section_ops@4",
  //   keyEvent: {
  //     key: "x",
  //     code: "KeyX",
  //     ctrlKey: true,
  //     shiftKey: true,
  //     bubbles: true,
  //     cancelable: true,
  //   },
  // },
  // Table
  {
    
    command: "new-table",
    title: "New Table",
    icon: "$(table)",
    keybinding: "ctrl+m",
    category: "Insert",
    contextGroup: "3_global_ops@2",
    keyEvent: {
      key: "m",
      code: "KeyM",
      ctrlKey: true,
      bubbles: true,
      cancelable: true,
    },
  },
  {
    command: "new-row-above",
    title: "Row (above)",
    icon: "$(arrow-up)",
    keybinding: "ctrl+shift+alt+f",
    category: "Table",
    selector: "table",
    contextKey: "webviewSection",
    vscWebviewContext: "table",
    contextGroup: "2_section_ops@2",
    keyEvent: {
      key: "f",
      code: "KeyF",
      ctrlKey: true,
      shiftKey: true,
      bubbles: true,
      cancelable: true,
    },
  },
  {
    command: "new-row-below",
    title: "Row (below)",
    icon: "$(arrow-down)",
    keybinding: "ctrl+=",
    category: "Table",
    selector: "table",
    contextKey: "webviewSection",
    vscWebviewContext: "table",
    contextGroup: "2_section_ops@2",
    keyEvent: {
      key: "=",
      code: "Equal",
      ctrlKey: true,
      bubbles: true,
      cancelable: true,
    },
  },
  {
    command: "del-row",
    title: "Delete Row",
    icon: "$(split-vertical)",
    keybinding: "ctrl+-",
    category: "Table",
    selector: "table",
    contextKey: "webviewItemElement",
    vscWebviewContext: "table-cell",
    contextGroup: "1_item_ops@2",
    keyEvent: {
      key: "-",
      code: "Minus",
      ctrlKey: true,
      bubbles: true,
      cancelable: true,
    },
  },
  {
    command: "new-col-left",
    title: "Col (L)",
    icon: "$(arrow-left)",
    keybinding: "ctrl+shift+g",
    category: "Table",
    selector: "table",
    contextKey: "webviewSection",
    vscWebviewContext: "table",
    contextGroup: "2_section_ops@2",
    keyEvent: {
      key: "g",
      code: "KeyG",
      ctrlKey: true,
      shiftKey: true,
      bubbles: true,
      cancelable: true,
    },
  },
  {
    command: "new-col-right",
    title: "Col (R)",
    icon: "$(arrow-right)",
    keybinding: "ctrl+shift+=",
    category: "Table",
    selector: "table",
    contextKey: "webviewSection",
    vscWebviewContext: "table",
    contextGroup: "2_section_ops@2",
    keyEvent: {
      key: "=",
      code: "Equal",
      ctrlKey: true,
      shiftKey: true,
      bubbles: true,
      cancelable: true,
    },
  },
  {
    command: "del-col",
    title: "Delete Col",
    icon: "$(split-horizontal)",
    keybinding: "ctrl+shift+-",
    category: "Table",
    selector: "table",
    contextKey: "webviewItemElement",
    vscWebviewContext: "table-cell",
    contextGroup: "1_item_ops@2",
    keyEvent: {
      key: "-",
      code: "Minus",
      ctrlKey: true,
      shiftKey: true,
      bubbles: true,
      cancelable: true,
    },
  },
  {
    command: "align-left",
    title: "Align (L)",
    icon: "$(layout-sidebar-left-dock)",
    keybinding: "ctrl+shift+l",
    category: "Table",
    selector: "table",
    contextKey: "webviewItemElement",
    vscWebviewContext: "table-cell",
    contextGroup: "1_item_ops@2",
    keyEvent: {
      key: "l",
      code: "KeyL",
      ctrlKey: true,
      shiftKey: true,
      bubbles: true,
      cancelable: true,
    },
  },
  {
    command: "align-center",
    title: "Align [C]",
    icon: "$(layout-centered)",
    keybinding: "ctrl+shift+c",
    category: "Table",
    selector: "table",
    contextKey: "webviewItemElement",
    vscWebviewContext: "table-cell",
    contextGroup: "1_item_ops@2",
    keyEvent: {
      key: "c",
      code: "KeyC",
      ctrlKey: true,
      shiftKey: true,
      bubbles: true,
      cancelable: true,
    },
  },
  {
    command: "align-right",
    title: "Align (R)",
    icon: "$(layout-sidebar-right-dock)",
    keybinding: "ctrl+shift+r",
    category: "Table",
    selector: "table",
    contextKey: "webviewItemElement",
    vscWebviewContext: "table-cell",
    contextGroup: "1_item_ops@2",
    keyEvent: {
      key: "r",
      code: "KeyR",
      ctrlKey: true,
      shiftKey: true,
      bubbles: true,
      cancelable: true,
    },
  },
  // {
  //   command: "move-caret-out",
  //   title: "Move Out",
  //   icon: "$(sign-out)",
  //   keybinding: "alt+enter",
  //   category: "Table",
  //   selector: "table",
  //   contextKey: "webviewItemElement",
  //   vscWebviewContext: "table-cell",
  //   contextGroup: "1_item_ops@3",
  //   keyEvent: {
  //     key: "Enter",
  //     code: "Enter",
  //     altKey: true,
  //     bubbles: true,
  //     cancelable: true,
  //   },
  // },
  {
    command: "move-caret-prev",
    title: "Move to Prev Cell",
    icon: "$(debug-step-back)",
    keybinding: "shift+tab",
    category: "Table",
    selector: "table",
    contextKey: "webviewItemElement",
    vscWebviewContext: "table-cell",
    contextGroup: "1_item_ops@3",
    keyEvent: {
      key: "Tab",
      code: "Tab",
      shiftKey: true,
      bubbles: true,
      cancelable: true,
    },
  },
  {
    command: "move-caret-next",
    title: "Move to Next Cell",
    icon: "$(debug-step-over)",
    keybinding: "tab",
    category: "Table",
    selector: "table",
    contextKey: "webviewItemElement",
    vscWebviewContext: "table-cell",
    contextGroup: "1_item_ops@3",
    keyEvent: {
      key: "Tab",
      code: "Tab",
      bubbles: true,
      cancelable: true,
    },
  },
  // Misc
  {
    command: "select-codeblock",
    title: "Select All Code Block",
    icon: "$(bracket-dot)",
    keybinding: "ctrl+a",
    category: "Code",
    selector: "[data-type='code-block']",
    contextGroup: "2_section_ops@3",
    keyEvent: {
      key: "a",
      code: "KeyA",
      ctrlKey: true,
      bubbles: true,
      cancelable: true,
    },
  },
  {
    command: "codeblock",
    title: "Code Block",
    icon: "$(code)",
    keybinding: "ctrl+u",
    category: "Insert",
    contextGroup: "3_global_ops@2",
    keyEvent: {
      key: "u",
      code: "KeyU",
      ctrlKey: true,
      bubbles: true,
      cancelable: true,
    },
  },
  {
    command: "blockquote",
    title: "Block Quote",
    icon: "$(quote)",
    keybinding: "ctrl+;",
    category: "Format",
    selector: "blockquote",
    contextKey: "webviewSection",
    vscWebviewContext: "blockquote",
    contextGroup: "2_section_ops@4",
    keyEvent: {
      key: ";",
      code: "Semicolon",
      ctrlKey: true,
      bubbles: true,
      cancelable: true,
    },
  },
  {
    command: "hr",
    title: "New Line",
    icon: "$(horizontal-rule)",
    keybinding: "ctrl+shift+h",
    category: "Insert",
    contextGroup: "3_global_ops@2",
    keyEvent: {
      key: "h",
      code: "KeyH",
      ctrlKey: true,
      shiftKey: true,
      bubbles: true,
      cancelable: true,
    },
  },
  {
    command: "undo",
    title: "Undo",
    icon: "$(discard)",
    keybinding: "ctrl+z",
    category: "System",
    contextGroup: "z_system@1",
    keyEvent: {
      key: "z",
      code: "KeyZ",
      ctrlKey: true,
      bubbles: true,
      cancelable: true,
    },
  },
  {
    command: "redo",
    title: "Redo",
    icon: "$(redo)",
    keybinding: "ctrl+y",
    category: "System",
    contextGroup: "z_system@1",
    keyEvent: {
      key: "y",
      code: "KeyY",
      ctrlKey: true,
      bubbles: true,
      cancelable: true,
    },
  },
];
