export const Features = [
  // Headings
  {
    command: "h1",
    title: "H1 Style Heading",
    icon: "$(symbol-number)",
    text: "H1",
    keybinding: "ctrl+alt+1",
    category: "Headings",
    selector: "h1",
    contextKey: "webviewSection",
    vscWebviewContext: "h1",
    contextGroup: "2_section_ops@4",
    keyEvent: {
      key: "1",
      code: "Digit1",
      ctrlKey: true,
      shiftKey: false,
      altKey: true,
      bubbles: true,
      cancelable: true,
    },
  },
  {
    command: "h2",
    title: "H2 Style Heading",
    icon: "$(symbol-number)",
    text: "H2",
    keybinding: "ctrl+alt+2",
    category: "Headings",
    selector: "h2",
    contextKey: "webviewSection",
    vscWebviewContext: "h2",
    contextGroup: "2_section_ops@4",
    keyEvent: {
      key: "2",
      code: "Digit2",
      ctrlKey: true,
      shiftKey: false,
      altKey: true,
      bubbles: true,
      cancelable: true,
    },
  },
  {
    command: "h3",
    title: "H3 Style Heading",
    icon: "$(symbol-number)",
    text: "H3",
    keybinding: "ctrl+alt+3",
    category: "Headings",
    selector: "h3",
    contextKey: "webviewSection",
    vscWebviewContext: "h3",
    contextGroup: "2_section_ops@4",
    keyEvent: {
      key: "3",
      code: "Digit3",
      ctrlKey: true,
      shiftKey: false,
      altKey: true,
      bubbles: true,
      cancelable: true,
    },
  },
  {
    command: "h4",
    title: "H4 Style Heading",
    icon: "$(symbol-number)",
    text: "H4",
    keybinding: "ctrl+alt+4",
    category: "Headings",
    selector: "h4",
    contextKey: "webviewSection",
    vscWebviewContext: "h4",
    contextGroup: "2_section_ops@4",
    keyEvent: {
      key: "4",
      code: "Digit4",
      ctrlKey: true,
      altKey: true,
      shiftKey: false,
      bubbles: true,
      cancelable: true,
    },
  },
  {
    command: "h5",
    title: "H5 Style Heading",
    icon: "$(symbol-number)",
    text: "H5",
    keybinding: "ctrl+alt+5",
    category: "Headings",
    selector: "h5",
    contextKey: "webviewSection",
    vscWebviewContext: "h5",
    contextGroup: "2_section_ops@4",
    keyEvent: {
      key: "5",
      code: "Digit5",
      ctrlKey: true,
      altKey: true,
      shiftKey: false,
      bubbles: true,
      cancelable: true,
    },
  },
  {
    command: "h6",
    title: "H6 Style Heading",
    icon: "$(symbol-number)",
    text: "H6",
    keybinding: "ctrl+alt+6",
    category: "Headings",
    selector: "h6",
    contextKey: "webviewSection",
    vscWebviewContext: "h6",
    contextGroup: "2_section_ops@4",
    keyEvent: {
      key: "6",
      code: "Digit6",
      ctrlKey: true,
      altKey: true,
      shiftKey: false,
      bubbles: true,
      cancelable: true,
    },
  },
  {
    command: "h+",
    title: "Increase Heading Level",
    icon: "$(diff-added)",
    text: "H+",
    keybinding: "ctrl+=",
    category: "Headings",
    contextGroup: "1_item_ops@4",
    keyEvent: {
      key: "=",
      code: "Equal",
      ctrlKey: true,
      bubbles: true,
      cancelable: true,
    },
  },
  {
    command: "h-",
    title: "Decrease Heading Level",
    icon: "$(diff-removed)",
    text: "H-",
    keybinding: "ctrl+-",
    category: "Headings",
    contextGroup: "1_item_ops@4",
    keyEvent: {
      key: "-",
      code: "Minus",
      ctrlKey: true,
      bubbles: true,
      cancelable: true,
    },
  },
  // Emphasis
  {
    command: "bold",
    title: "Bold",
    icon: "$(bold)",
    text: "Bold",
    keybinding: "ctrl+b",
    category: "Emphasis",
    contextGroup: "3_global_ops@1",
    keyEvent: {
      key: "b",
      code: "KeyB",
      ctrlKey: true,
      altKey: false,
      shiftKey: false,
      bubbles: true,
      cancelable: true,
    },
  },
  {
    command: "italic",
    title: "Italic",
    icon: "$(italic)",
    text: "Italic",
    keybinding: "ctrl+i",
    category: "Emphasis",
    contextGroup: "3_global_ops@1",
    keyEvent: {
      key: "i",
      code: "KeyI",
      ctrlKey: true,
      altKey: false,
      shiftKey: false,
      bubbles: true,
      cancelable: true,
    },
  },
  {
    command: "strikethrough",
    title: "Strike",
    icon: "$(strikethrough)",
    text: "Strike",
    keybinding: "ctrl+s",
    category: "Emphasis",
    contextGroup: "3_global_ops@1",
    keyEvent: {
      key: "s",
      code: "KeyS",
      ctrlKey: true,
      altKey: false,
      shiftKey: false,
      bubbles: true,
      cancelable: true,
    },
  },
  {
    command: "link",
    title: "Link",
    icon: "$(link)",
    text: "Link",
    keybinding: "ctrl+k",
    category: "Emphasis",
    selector: "a",
    contextKey: "webviewItemElement",
    vscWebviewContext: "link",
    contextGroup: "1_item_ops@5",
    keyEvent: {
      key: "k",
      code: "KeyK",
      ctrlKey: true,
      altKey: false,
      shiftKey: false,
      bubbles: true,
      cancelable: true,
    },
  },
  {
    command: "inlinecode",
    title: "Monospace",
    icon: "$(symbol-string)",
    text: "Quote",
    keybinding: "ctrl+g",
    category: "Emphasis",
    contextGroup: "3_global_ops@1",
    keyEvent: {
      key: "g",
      code: "KeyG",
      ctrlKey: true,
      altKey: false,
      shiftKey: false,
      bubbles: true,
      cancelable: true,
    },
  },
  // Lists
  {
    command: "unordered",
    title: "Unordered List",
    icon: "$(list-unordered)",
    text: "UL",
    keybinding: "ctrl+l",
    category: "Lists",
    selector: "ul",
    contextKey: "webviewSection",
    vscWebviewContext: "unordered",
    contextGroup: "2_section_ops@1",
    keyEvent: {
      key: "l",
      code: "KeyL",
      ctrlKey: true,
      altKey: false,
      shiftKey: false,
      bubbles: true,
      cancelable: true,
    },
  },
  {
    command: "ordered",
    title: "Ordered List",
    icon: "$(list-ordered)",
    text: "OL",
    keybinding: "ctrl+o",
    category: "Lists",
    selector: "ol",
    contextKey: "webviewSection",
    vscWebviewContext: "ordered",
    contextGroup: "2_section_ops@1",
    keyEvent: {
      key: "o",
      code: "KeyO",
      ctrlKey: true,
      altKey: false,
      shiftKey: false,
      bubbles: true,
      cancelable: true,
    },
  },
  {
    command: "checked",
    title: "Checked List",
    icon: "$(tasklist)",
    text: "Checked",
    keybinding: "ctrl+j",
    category: "Lists",
    selector: "li",
    contextKey: "webviewItemElement",
    vscWebviewContext: "list-item",
    contextGroup: "1_item_ops@1",
    keyEvent: {
      key: "j",
      code: "KeyJ",
      ctrlKey: true,
      altKey: false,
      shiftKey: false,
      bubbles: true,
      cancelable: true,
    },
  },
  {
    command: "checked-toggle",
    title: "Toggle Checkbox Tick",
    icon: "$(check)",
    keybinding: "ctrl+shift+j",
    category: "Lists",
    selector: "li",
    contextKey: "webviewItemElement",
    vscWebviewContext: "list-item",
    contextGroup: "1_item_ops@1",
    keyEvent: {
      key: "j",
      code: "KeyJ",
      ctrlKey: true,
      shiftKey: true,
      bubbles: true,
      cancelable: true,
    },
  },
  {
    command: "indent",
    title: "Indent List",
    icon: "$(indent)",
    keybinding: "ctrl+shift+i",
    category: "Lists",
    selector: "li",
    contextKey: "webviewItemElement",
    vscWebviewContext: "list-item",
    contextGroup: "1_item_ops@1",
    keyEvent: {
      key: "i",
      code: "KeyI",
      ctrlKey: true,
      shiftKey: true,
      bubbles: true,
      cancelable: true,
    },
  },
  {
    command: "unindent",
    title: "Unindent List",
    icon: "$(newline)",
    keybinding: "ctrl+shift+o",
    category: "Lists",
    selector: "li",
    contextKey: "webviewItemElement",
    vscWebviewContext: "list-item",
    contextGroup: "1_item_ops@1",
    keyEvent: {
      key: "o",
      code: "KeyO",
      ctrlKey: true,
      shiftKey: true,
      bubbles: true,
      cancelable: true,
    },
  },
  // Block Elements
  {
    command: "new-start",
    title: "New Block to Before",
    icon: "$(arrow-up)",
    keybinding: "ctrl+shift+b",
    category: "Blocks",
    contextGroup: "2_section_ops@4",
    keyEvent: {
      key: "b",
      code: "KeyB",
      ctrlKey: true,
      shiftKey: true,
      bubbles: true,
      cancelable: true,
    },
  },
  {
    command: "new-end",
    title: "New Block to End",
    icon: "$(arrow-down)",
    keybinding: "ctrl+shift+e",
    category: "Blocks",
    contextGroup: "2_section_ops@4",
    keyEvent: {
      key: "e",
      code: "KeyE",
      ctrlKey: true,
      shiftKey: true,
      bubbles: true,
      cancelable: true,
    },
  },
  {
    command: "move-up",
    title: "Move Block Up",
    icon: "$(arrow-circle-up)",
    keybinding: "ctrl+shift+u",
    category: "Blocks",
    contextGroup: "2_section_ops@4",
    keyEvent: {
      key: "u",
      code: "KeyU",
      ctrlKey: true,
      shiftKey: true,
      bubbles: true,
      cancelable: true,
    },
  },
  {
    command: "move-down",
    title: "Move Block Down",
    icon: "$(arrow-circle-up)",
    keybinding: "ctrl+shift+d",
    category: "Blocks",
    contextGroup: "2_section_ops@4",
    keyEvent: {
      key: "d",
      code: "KeyD",
      ctrlKey: true,
      shiftKey: true,
      bubbles: true,
      cancelable: true,
    },
  },
  {
    command: "remove",
    title: "Remove Block",
    icon: "$(trash)",
    keybinding: "ctrl+shift+x",
    category: "Blocks",
    contextGroup: "2_section_ops@4",
    keyEvent: {
      key: "x",
      code: "KeyX",
      ctrlKey: true,
      shiftKey: true,
      bubbles: true,
      cancelable: true,
    },
  },
  // Table
  {
    command: "new-table",
    title: "New Table",
    icon: "$(table)",
    keybinding: "ctrl+m",
    category: "Tables",
    contextGroup: "3_global_ops@2",
    keyEvent: {
      key: "m",
      code: "KeyM",
      ctrlKey: true,
      bubbles: true,
      cancelable: true,
    },
  },
  {
    command: "new-row-above",
    title: "New Row Above",
    icon: "$(arrow-up)",
    keybinding: "ctrl+shift+f",
    category: "Tables",
    selector: "table",
    contextKey: "webviewSection",
    vscWebviewContext: "table",
    contextGroup: "2_section_ops@2",
    keyEvent: {
      key: "f",
      code: "KeyF",
      ctrlKey: true,
      shiftKey: true,
      bubbles: true,
      cancelable: true,
    },
  },
  {
    command: "new-row-below",
    title: "New Row Below",
    icon: "$(arrow-down)",
    keybinding: "ctrl+=",
    category: "Tables",
    selector: "table",
    contextKey: "webviewSection",
    vscWebviewContext: "table",
    contextGroup: "2_section_ops@2",
    keyEvent: {
      key: "=",
      code: "Equal",
      ctrlKey: true,
      bubbles: true,
      cancelable: true,
    },
  },
  {
    command: "del-row",
    title: "Delete Row",
    icon: "$(split-vertical)",
    keybinding: "ctrl+-",
    category: "Tables",
    selector: "table",
    contextKey: "webviewItemElement",
    vscWebviewContext: "table-cell",
    contextGroup: "1_item_ops@2",
    keyEvent: {
      key: "-",
      code: "Minus",
      ctrlKey: true,
      bubbles: true,
      cancelable: true,
    },
  },
  {
    command: "new-col-left",
    title: "New Column Left",
    icon: "$(arrow-left)",
    keybinding: "ctrl+shift+g",
    category: "Tables",
    selector: "table",
    contextKey: "webviewSection",
    vscWebviewContext: "table",
    contextGroup: "2_section_ops@2",
    keyEvent: {
      key: "g",
      code: "KeyG",
      ctrlKey: true,
      shiftKey: true,
      bubbles: true,
      cancelable: true,
    },
  },
  {
    command: "new-col-right",
    title: "New Column Right",
    icon: "$(arrow-right)",
    keybinding: "ctrl+shift+=",
    category: "Tables",
    selector: "table",
    contextKey: "webviewSection",
    vscWebviewContext: "table",
    contextGroup: "2_section_ops@2",
    keyEvent: {
      key: "=",
      code: "Equal",
      ctrlKey: true,
      shiftKey: true,
      bubbles: true,
      cancelable: true,
    },
  },
  {
    command: "del-col",
    title: "Delete Column",
    icon: "$(split-horizontal)",
    keybinding: "ctrl+shift+-",
    category: "Tables",
    selector: "table",
    contextKey: "webviewItemElement",
    vscWebviewContext: "table-cell",
    contextGroup: "1_item_ops@2",
    keyEvent: {
      key: "-",
      code: "Minus",
      ctrlKey: true,
      shiftKey: true,
      bubbles: true,
      cancelable: true,
    },
  },
  {
    command: "align-left",
    title: "Align Left",
    icon: "$(layout-sidebar-left-dock)",
    keybinding: "ctrl+shift+l",
    category: "Tables",
    selector: "table",
    contextKey: "webviewItemElement",
    vscWebviewContext: "table-cell",
    contextGroup: "1_item_ops@2",
    keyEvent: {
      key: "l",
      code: "KeyL",
      ctrlKey: true,
      shiftKey: true,
      bubbles: true,
      cancelable: true,
    },
  },
  {
    command: "align-center",
    title: "Align Center",
    icon: "$(layout-centered)",
    keybinding: "ctrl+shift+c",
    category: "Tables",
    selector: "table",
    contextKey: "webviewItemElement",
    vscWebviewContext: "table-cell",
    contextGroup: "1_item_ops@2",
    keyEvent: {
      key: "c",
      code: "KeyC",
      ctrlKey: true,
      shiftKey: true,
      bubbles: true,
      cancelable: true,
    },
  },
  {
    command: "align-right",
    title: "Align Right",
    icon: "$(layout-sidebar-right-dock)",
    keybinding: "ctrl+shift+r",
    category: "Tables",
    selector: "table",
    contextKey: "webviewItemElement",
    vscWebviewContext: "table-cell",
    contextGroup: "1_item_ops@2",
    keyEvent: {
      key: "r",
      code: "KeyR",
      ctrlKey: true,
      shiftKey: true,
      bubbles: true,
      cancelable: true,
    },
  },
  {
    command: "move-caret-out",
    title: "Move Out",
    icon: "$(sign-out)",
    keybinding: "alt+enter",
    category: "Tables",
    selector: "table",
    contextKey: "webviewItemElement",
    vscWebviewContext: "table-cell",
    contextGroup: "1_item_ops@3",
    keyEvent: {
      key: "Enter",
      code: "Enter",
      altKey: true,
      bubbles: true,
      cancelable: true,
    },
  },
  {
    command: "move-caret-prev",
    title: "Move to Prev Cell",
    icon: "$(debug-step-back)",
    keybinding: "shift+tab",
    category: "Tables",
    selector: "table",
    contextKey: "webviewItemElement",
    vscWebviewContext: "table-cell",
    contextGroup: "1_item_ops@3",
    keyEvent: {
      key: "Tab",
      code: "Tab",
      shiftKey: true,
      bubbles: true,
      cancelable: true,
    },
  },
  {
    command: "move-caret-next",
    title: "Move to Next Cell",
    icon: "$(debug-step-over)",
    keybinding: "tab",
    category: "Tables",
    selector: "table",
    contextKey: "webviewItemElement",
    vscWebviewContext: "table-cell",
    contextGroup: "1_item_ops@3",
    keyEvent: {
      key: "Tab",
      code: "Tab",
      bubbles: true,
      cancelable: true,
    },
  },
  // Misc
  {
    command: "select-codeblock",
    title: "Select All Code Block",
    icon: "$(select-all)",
    keybinding: "ctrl+a",
    category: "Misc",
    contextGroup: "2_section_ops@3",
    keyEvent: {
      key: "a",
      code: "KeyA",
      ctrlKey: true,
      bubbles: true,
      cancelable: true,
    },
  },
  {
    command: "codeblock",
    title: "Code Block",
    icon: "$(code)",
    keybinding: "ctrl+u",
    category: "Misc",
    contextGroup: "3_global_ops@2",
    keyEvent: {
      key: "u",
      code: "KeyU",
      ctrlKey: true,
      bubbles: true,
      cancelable: true,
    },
  },
  {
    command: "blockquote",
    title: "Block Quote",
    icon: "$(quote)",
    keybinding: "ctrl+;",
    category: "Misc",
    selector: "blockquote",
    contextKey: "webviewSection",
    vscWebviewContext: "blockquote",
    contextGroup: "2_section_ops@4",
    keyEvent: {
      key: ";",
      code: "Semicolon",
      ctrlKey: true,
      bubbles: true,
      cancelable: true,
    },
  },
  {
    command: "hr",
    title: "Line",
    icon: "$(horizontal-rule)",
    keybinding: "ctrl+shift+h",
    category: "Misc",
    contextGroup: "3_global_ops@2",
    keyEvent: {
      key: "h",
      code: "KeyH",
      ctrlKey: true,
      shiftKey: true,
      bubbles: true,
      cancelable: true,
    },
  },
  {
    command: "undo",
    title: "Undo",
    icon: "$(discard)",
    keybinding: "ctrl+z",
    category: "System",
    contextGroup: "z_system@1",
    keyEvent: {
      key: "z",
      code: "KeyZ",
      ctrlKey: true,
      bubbles: true,
      cancelable: true,
    },
  },
  {
    command: "redo",
    title: "Redo",
    icon: "$(redo)",
    keybinding: "ctrl+y",
    category: "System",
    contextGroup: "z_system@1",
    keyEvent: {
      key: "y",
      code: "KeyY",
      ctrlKey: true,
      bubbles: true,
      cancelable: true,
    },
  },
];

export const ExtendedFeatures = [
  // Extended
  {
    command: "toggle",
    title: "Toggle Default/Mark↓Pen Editors",
    icon: "$(multiple-windows)",
    text: "Toggle",
    keybinding: "ctrl+alt+e",
  },
];