export const Features = [
  // Heading
  {
    command: "h0",
    title: "Remove Heading",
    icon: "$(symbol-number)0",
    keybinding: "ctrl+h",
    category: "Heading",
    selector: "h1",
    hotkey: "ctrl+h",
  },
  {
    command: "h1",
    title: "H1 Style Heading",
    icon: "$(symbol-number)1",
    keybinding: "ctrl+alt+1",
    category: "Heading",
    selector: "h1",
    hotkey: "ctrl+alt+1",
  },
  {
    command: "h2",
    title: "H2 Style Heading",
    icon: "$(symbol-number)2",
    keybinding: "ctrl+alt+2",
    category: "Heading",
    selector: "h2",
    hotkey: "ctrl+alt+2",
  },
  {
    command: "h3",
    title: "H3 Style Heading",
    icon: "$(symbol-number)3",
    keybinding: "ctrl+alt+3",
    category: "Heading",
    selector: "h3",
    hotkey: "ctrl+alt+3",
  },
  {
    command: "h4",
    title: "H4 Style Heading",
    icon: "$(symbol-number)4",
    keybinding: "ctrl+alt+4",
    category: "Heading",
    selector: "h4",
    hotkey: "ctrl+alt+4",
  },
  {
    command: "h5",
    title: "H5 Style Heading",
    icon: "$(symbol-number)5",
    keybinding: "ctrl+alt+5",
    category: "Heading",
    selector: "h5",
    hotkey: "ctrl+alt+5",
  },
  {
    command: "h6",
    title: "H6 Style Heading",
    icon: "$(symbol-number)6",
    keybinding: "ctrl+alt+6",
    category: "Heading",
    selector: "h6",
    hotkey: "ctrl+alt+6",
  },
  {
    command: "h+",
    title: "Heading Level +1",
    icon: "$(symbol-number)+",
    keybinding: "ctrl+=",
    category: "Heading",
    hotkey: "ctrl+=",
  },
  {
    command: "h-",
    title: "Heading Level - 1",
    icon: "$(symbol-number)-",
    keybinding: "ctrl+-",
    category: "Heading",
    hotkey: "ctrl+-",
  },
  // Format
  {
    command: "bold",
    title: "Bold",
    icon: "$(bold)",
    keybinding: "ctrl+b",
    category: "Format",
    hotkey: "ctrl+b",
  },
  {
    command: "italic",
    title: "Italic",
    icon: "$(italic)",
    keybinding: "ctrl+i",
    category: "Format",
    hotkey: "ctrl+i",
  },
  {
    command: "strikethrough",
    title: "Strike",
    icon: "$(strikethrough)",
    keybinding: "ctrl+d",
    category: "Format",
    hotkey: "ctrl+d",
  },
  {
    command: "link",
    title: "Link",
    icon: "$(link)",
    keybinding: "ctrl+k",
    category: "Format",
    selector: "a",
    hotkey: "ctrl+k",
  },
  {
    command: "inlinecode",
    title: "Monospace",
    icon: "$(symbol-string)",
    keybinding: "ctrl+g",
    category: "Format",
    hotkey: "ctrl+g",
  },
  {
    command: "unordered",
    title: "Unordered List",
    icon: "$(list-unordered)",
    keybinding: "ctrl+l",
    category: "Format",
    selector: "ul",
    hotkey: "ctrl+l",
  },
  {
    command: "ordered",
    title: "Ordered List",
    icon: "$(list-ordered)",
    keybinding: "ctrl+o",
    category: "Format",
    selector: "ol",
    hotkey: "ctrl+o",
  },
  {
    command: "checked",
    title: "Checked List",
    icon: "$(tasklist)",
    keybinding: "ctrl+j",
    category: "Format",
    selector: "ul",
    hotkey: "ctrl+j",
  },
  // List
  {
    command: "checked-toggle",
    title: "Toggle Tick",
    icon: "$(check)",
    keybinding: "ctrl+shift+j",
    category: "List",
    selector: "li.vditor-task",
    hotkey: "ctrl+shift+j",
  },
  {
    command: "indent",
    title: "(L) Indent",
    icon: "$(indent)",
    keybinding: "ctrl+shift+i",
    category: "List",
    selector: "li",
    hotkey: "ctrl+shift+i",
  },
  {
    command: "unindent",
    title: "(R) Indent",
    icon: "$(newline)",
    keybinding: "ctrl+shift+o",
    category: "List",
    selector: "li",
    hotkey: "ctrl+shift+o",
  },
  // Block Elements
  {
    command: "new-start",
    title: "Empty Paragraph (before)",
    icon: "$(arrow-up)",
    keybinding: "ctrl+shift+b",
    category: "Insert",
    hotkey: "ctrl+shift+b",
  },
  {
    command: "new-end",
    title: "Empty Paragraph",
    icon: "$(arrow-down)",
    keybinding: "ctrl+shift+e",
    category: "Insert",
    hotkey: "ctrl+shift+e",
  },
  // Table
  {
    command: "new-table",
    title: "Empty 3x3 Table",
    icon: "$(table)",
    keybinding: "ctrl+m",
    category: "Insert",
    hotkey: "ctrl+m",
  },
  {
    command: "new-row-above",
    title: "Row (above)",
    icon: "$(arrow-up)",
    keybinding: "ctrl+shift+alt+f",
    category: "Table",
    selector: "table",
    hotkey: "ctrl+shift+f",
  },
  {
    command: "new-row-below",
    title: "Row (below)",
    icon: "$(arrow-down)",
    keybinding: "ctrl+=",
    category: "Table",
    selector: "table",
    hotkey: "ctrl+=",
  },
  {
    command: "del-row",
    title: "Delete Row",
    icon: "$(split-vertical)",
    keybinding: "ctrl+-",
    category: "Table",
    selector: "table",
    hotkey: "ctrl+-",
  },
  {
    command: "new-col-left",
    title: "Col (L)",
    icon: "$(arrow-left)",
    keybinding: "ctrl+shift+g",
    category: "Table",
    selector: "table",
    hotkey: "ctrl+shift+g",
  },
  {
    command: "new-col-right",
    title: "Col (R)",
    icon: "$(arrow-right)",
    keybinding: "ctrl+shift+=",
    category: "Table",
    selector: "table",
    hotkey: "ctrl+shift+=",
  },
  {
    command: "del-col",
    title: "Delete Col",
    icon: "$(split-horizontal)",
    keybinding: "ctrl+shift+-",
    category: "Table",
    selector: "table",
    hotkey: "ctrl+shift+-",
  },
  {
    command: "align-left",
    title: "Align (L)",
    icon: "$(layout-sidebar-left-dock)",
    keybinding: "ctrl+shift+l",
    category: "Table",
    selector: "table",
    hotkey: "ctrl+shift+l",
  },
  {
    command: "align-center",
    title: "Align [C]",
    icon: "$(layout-centered)",
    keybinding: "ctrl+shift+c",
    category: "Table",
    selector: "table",
    hotkey: "ctrl+shift+c",
  },
  {
    command: "align-right",
    title: "Align (R)",
    icon: "$(layout-sidebar-right-dock)",
    keybinding: "ctrl+shift+r",
    category: "Table",
    selector: "table",
    hotkey: "ctrl+shift+r",
  },
  {
    command: "move-caret-prev",
    title: "Move to Prev Cell",
    icon: "$(debug-step-back)",
    keybinding: "shift+tab",
    category: "Table",
    selector: "table",
    hotkey: "shift+tab",
  },
  {
    command: "move-caret-next",
    title: "Move to Next Cell",
    icon: "$(debug-step-over)",
    keybinding: "tab",
    category: "Table",
    selector: "table",
    hotkey: "tab",
  },
  // Misc
  {
    command: "select-codeblock",
    title: "Select All Code Block",
    icon: "$(bracket-dot)",
    keybinding: "ctrl+a",
    category: "Code",
    selector: "[data-type='code-block']",
    hotkey: "ctrl+a",
  },
  {
    command: "codeblock",
    title: "Fenced Code Block",
    icon: "$(code)",
    keybinding: "ctrl+u",
    category: "Insert",
    hotkey: "ctrl+u",
  },
  {
    command: "blockquote",
    title: "Block Quote",
    icon: "$(quote)",
    keybinding: "ctrl+;",
    category: "Format",
    selector: "blockquote",
    hotkey: "ctrl+;",
  },
  {
    command: "hr",
    title: "Horizontal Line",
    icon: "$(horizontal-rule)",
    keybinding: "ctrl+shift+h",
    category: "Insert",
    hotkey: "ctrl+shift+h",
  },
  {
    command: "undo",
    title: "Undo",
    icon: "$(discard)",
    keybinding: "ctrl+z",
    category: "System",
    hotkey: "ctrl+z",
  },
  {
    command: "redo",
    title: "Redo",
    icon: "$(redo)",
    keybinding: "ctrl+y",
    category: "System",
    hotkey: "ctrl+y",
  },
];
