export const Hotkeys = [
  {
    command: "vsc-markdown.insertH1",
    title: "Insert H1 Heading",
    icon: "$(symbol-text)",
    text: "H1",
    keybinding: "ctrl+alt+1",
    keyEvent: {
      key: "1",
      code: "Digit1",
      ctrlKey: true,
      altKey: true,
      bubbles: true,
      cancelable: true,
    },
  },
  {
    command: "vsc-markdown.insertH2",
    title: "Insert H2 Heading",
    icon: "$(symbol-text)",
    text: "H2",
    keybinding: "ctrl+alt+2",
    keyEvent: {
      key: "2",
      code: "Digit2",
      ctrlKey: true,
      altKey: true,
      bubbles: true,
      cancelable: true,
    },
  },
  {
    command: "vsc-markdown.insertH3",
    title: "Insert H3 Heading",
    icon: "$(symbol-text)",
    text: "H3",
    keybinding: "ctrl+alt+3",
    keyEvent: {
      key: "3",
      code: "Digit3",
      ctrlKey: true,
      altKey: true,
      bubbles: true,
      cancelable: true,
    },
  },
  {
    command: "vsc-markdown.insertH4",
    title: "Insert H4 Heading",
    icon: "$(symbol-text)",
    text: "H4",
    keybinding: "ctrl+alt+4",
    keyEvent: {
      key: "4",
      code: "Digit4",
      ctrlKey: true,
      altKey: true,
      bubbles: true,
      cancelable: true,
    },
  },
  {
    command: "vsc-markdown.insertH5",
    title: "Insert H5 Heading",
    icon: "$(symbol-text)",
    text: "H5",
    keybinding: "ctrl+alt+5",
    keyEvent: {
      key: "5",
      code: "Digit5",
      ctrlKey: true,
      altKey: true,
      bubbles: true,
      cancelable: true,
    },
  },
  {
    command: "vsc-markdown.insertBold",
    title: "Insert Bold Text",
    icon: "$(bold)",
    keybinding: "ctrl+b",
    keyEvent: {
      key: "b",
      code: "KeyB",
      ctrlKey: true,
      bubbles: true,
      cancelable: true,
    },
  },
  {
    command: "vsc-markdown.insertItalic",
    title: "Insert Italic Text",
    icon: "$(italic)",
    keybinding: "ctrl+i",
    keyEvent: {
      key: "i",
      code: "KeyI",
      ctrlKey: true,
      bubbles: true,
      cancelable: true,
    },
  },
  {
    command: "vsc-markdown.insertList",
    title: "Insert Unordered List",
    icon: "$(list-unordered)",
    keybinding: "ctrl+l",
    keyEvent: {
      key: "l",
      code: "KeyL",
      ctrlKey: true,
      bubbles: true,
      cancelable: true,
    },
  },
  {
    command: "vsc-markdown.insertOrderedList",
    title: "Insert Ordered List",
    icon: "$(list-ordered)",
    keybinding: "ctrl+o",
    keyEvent: {
      key: "o",
      code: "KeyO",
      ctrlKey: true,
      bubbles: true,
      cancelable: true,
    },
  },
  {
    command: "vsc-markdown.insertLink",
    title: "Insert Link",
    icon: "$(link)",
    keybinding: "ctrl+k",
    keyEvent: {
      key: "k",
      code: "KeyK",
      ctrlKey: true,
      bubbles: true,
      cancelable: true,
    },
  },
  {
    command: "vsc-markdown.insertImage",
    title: "Insert Image",
    icon: "$(file-media)",
    keybinding: "",
  },
  {
    command: "vsc-markdown.insertCodeBlock",
    title: "Insert Code Block",
    icon: "$(code)",
    keybinding: "ctrl+u",
    keyEvent: {
      key: "u",
      code: "KeyU",
      ctrlKey: true,
      bubbles: true,
      cancelable: true,
    },
  },
  {
    command: "vsc-markdown.insertInlineCode",
    title: "Insert Inline Code",
    icon: "$(symbol-string)",
    keybinding: "ctrl+g",
    keyEvent: {
      key: "g",
      code: "KeyG",
      ctrlKey: true,
      bubbles: true,
      cancelable: true,
    },
  },
  {
    command: "vsc-markdown.insertBlockquote",
    title: "Insert Blockquote",
    icon: "$(quote)",
    keybinding: "ctrl+;",
    keyEvent: {
      key: ";",
      code: "Semicolon",
      ctrlKey: true,
      bubbles: true,
      cancelable: true,
    },
  },
  {
    command: "vsc-markdown.insertTable",
    title: "Insert Table",
    icon: "$(table)",
    keybinding: "ctrl+m",
    keyEvent: {
      key: "m",
      code: "KeyM",
      ctrlKey: true,
      bubbles: true,
      cancelable: true,
    },
  },
  {
    command: "vsc-markdown.insertStrikethrough",
    title: "Insert Strikethrough",
    icon: "$(strikethrough)",
    keybinding: "ctrl+s",
    keyEvent: {
      key: "s",
      code: "KeyS",
      ctrlKey: true,
      bubbles: true,
      cancelable: true,
    },
  },
  {
    command: "vsc-markdown.insertEmptyBlock",
    title: "Insert Empty Block",
    icon: "$(add)",
    keybinding: "",
  },
  {
    command: "vsc-markdown.insertTaskList",
    title: "Insert Task List",
    icon: "$(tasklist)",
    keybinding: "ctrl+j",
    keyEvent: {
      key: "j",
      code: "KeyJ",
      ctrlKey: true,
      bubbles: true,
      cancelable: true,
    },
  },
  {
    command: "vsc-markdown.insertHorizontalRule",
    title: "Insert Horizontal Rule",
    icon: "$(dash)",
    keybinding: "ctrl+shift+h",
    keyEvent: {
      key: "h",
      code: "KeyH",
      ctrlKey: true,
      shiftKey: true,
      bubbles: true,
      cancelable: true,
    },
  },
  {
    command: "vsc-markdown.insertBlockBefore",
    title: "Insert Block to Before",
    icon: "$(arrow-up)",
    keybinding: "ctrl+shift+b",
    keyEvent: {
      key: "b",
      code: "KeyB",
      ctrlKey: true,
      shiftKey: true,
      bubbles: true,
      cancelable: true,
    },
  },
  {
    command: "vsc-markdown.insertBlockEnd",
    title: "Insert Block to End",
    icon: "$(arrow-down)",
    keybinding: "ctrl+shift+e",
    keyEvent: {
      key: "e",
      code: "KeyE",
      ctrlKey: true,
      shiftKey: true,
      bubbles: true,
      cancelable: true,
    },
  },
  {
    command: "vsc-markdown.undo",
    title: "Undo",
    icon: "$(undo)",
    keybinding: "ctrl+z",
    keyEvent: {
      key: "z",
      code: "KeyZ",
      ctrlKey: true,
      bubbles: true,
      cancelable: true,
    },
  },
  {
    command: "vsc-markdown.redo",
    title: "Redo",
    icon: "$(redo)",
    keybinding: "ctrl+y",
    keyEvent: {
      key: "y",
      code: "KeyY",
      ctrlKey: true,
      bubbles: true,
      cancelable: true,
    },
  },
  {
    command: "vsc-markdown.moveBlockUp",
    title: "Move Block Up",
    icon: "$(arrow-up)",
    keybinding: "ctrl+shift+u",
    keyEvent: {
      key: "u",
      code: "KeyU",
      ctrlKey: true,
      shiftKey: true,
      bubbles: true,
      cancelable: true,
    },
  },
  {
    command: "vsc-markdown.moveBlockDown",
    title: "Move Block Down",
    icon: "$(arrow-down)",
    keybinding: "ctrl+shift+d",
    keyEvent: {
      key: "d",
      code: "KeyD",
      ctrlKey: true,
      shiftKey: true,
      bubbles: true,
      cancelable: true,
    },
  },
  // {
  //   command: "vsc-markdown.toggleFullscreen",
  //   title: "Toggle Fullscreen",
  //   icon: "$(screen-full)",
  //   keybinding: "ctrl+'",
  //   keyEvent: {
  //     key: "'",
  //     code: "Quote",
  //     ctrlKey: true,
  //     bubbles: true,
  //     cancelable: true,
  //   },
  // },
  {
    command: "vsc-markdown.increaseHeading",
    title: "Increase Heading Level",
    icon: "$(arrow-up)",
    keybinding: "ctrl+=",
    keyEvent: {
      key: "=",
      code: "Equal",
      ctrlKey: true,
      bubbles: true,
      cancelable: true,
    },
  },
  {
    command: "vsc-markdown.decreaseHeading",
    title: "Decrease Heading Level",
    icon: "$(arrow-down)",
    keybinding: "ctrl+-",
    keyEvent: {
      key: "-",
      code: "Minus",
      ctrlKey: true,
      bubbles: true,
      cancelable: true,
    },
  },
  {
    command: "vsc-markdown.indentList",
    title: "Indent List",
    icon: "$(indent)",
    keybinding: "tab",
    keyEvent: {
      key: "Tab",
      code: "Tab",
      bubbles: true,
      cancelable: true,
    },
  },
  {
    command: "vsc-markdown.unindentList",
    title: "Unindent List",
    icon: "$(outdent)",
    keybinding: "shift+tab",
    keyEvent: {
      key: "Tab",
      code: "Tab",
      shiftKey: true,
      bubbles: true,
      cancelable: true,
    },
  },
  {
    command: "vsc-markdown.toggleTaskCheck",
    title: "Toggle Task Check",
    icon: "$(check)",
    keybinding: "ctrl+shift+j",
    keyEvent: {
      key: "j",
      code: "KeyJ",
      ctrlKey: true,
      shiftKey: true,
      bubbles: true,
      cancelable: true,
    },
  },
  {
    command: "vsc-markdown.insertTableRowAbove",
    title: "Insert Table Row Above",
    icon: "$(arrow-up)",
    keybinding: "ctrl+shift+f",
    keyEvent: {
      key: "f",
      code: "KeyF",
      ctrlKey: true,
      shiftKey: true,
      bubbles: true,
      cancelable: true,
    },
  },
  {
    command: "vsc-markdown.insertTableRowBelow",
    title: "Insert Table Row Below",
    icon: "$(arrow-down)",
    keybinding: "ctrl+=",
    keyEvent: {
      key: "=",
      code: "Equal",
      ctrlKey: true,
      bubbles: true,
      cancelable: true,
    },
  },
  {
    command: "vsc-markdown.deleteTableRow",
    title: "Delete Table Row",
    icon: "$(trash)",
    keybinding: "ctrl+-",
    keyEvent: {
      key: "-",
      code: "Minus",
      ctrlKey: true,
      bubbles: true,
      cancelable: true,
    },
  },
  {
    command: "vsc-markdown.insertTableColLeft",
    title: "Insert Table Column Left",
    icon: "$(arrow-left)",
    keybinding: "ctrl+shift+g",
    keyEvent: {
      key: "g",
      code: "KeyG",
      ctrlKey: true,
      shiftKey: true,
      bubbles: true,
      cancelable: true,
    },
  },
  {
    command: "vsc-markdown.insertTableColRight",
    title: "Insert Table Column Right",
    icon: "$(arrow-right)",
    keybinding: "ctrl+shift+=",
    keyEvent: {
      key: "=",
      code: "Equal",
      ctrlKey: true,
      shiftKey: true,
      bubbles: true,
      cancelable: true,
    },
  },
  {
    command: "vsc-markdown.deleteTableCol",
    title: "Delete Table Column",
    icon: "$(trash)",
    keybinding: "ctrl+shift+-",
    keyEvent: {
      key: "-",
      code: "Minus",
      ctrlKey: true,
      shiftKey: true,
      bubbles: true,
      cancelable: true,
    },
  },
  {
    command: "vsc-markdown.tableAlignLeft",
    title: "Table Align Left",
    icon: "$(align-left)",
    keybinding: "ctrl+shift+l",
    keyEvent: {
      key: "l",
      code: "KeyL",
      ctrlKey: true,
      shiftKey: true,
      bubbles: true,
      cancelable: true,
    },
  },
  {
    command: "vsc-markdown.tableAlignCenter",
    title: "Table Align Center",
    icon: "$(align-center)",
    keybinding: "ctrl+shift+c",
    keyEvent: {
      key: "c",
      code: "KeyC",
      ctrlKey: true,
      shiftKey: true,
      bubbles: true,
      cancelable: true,
    },
  },
  {
    command: "vsc-markdown.tableAlignRight",
    title: "Table Align Right",
    icon: "$(align-right)",
    keybinding: "ctrl+shift+r",
    keyEvent: {
      key: "r",
      code: "KeyR",
      ctrlKey: true,
      shiftKey: true,
      bubbles: true,
      cancelable: true,
    },
  },
  {
    command: "vsc-markdown.insertEmoji",
    title: "Insert Emoji",
    icon: "$(smiley)",
    keybinding: ":",
    keyEvent: {
      key: ":",
      code: "Semicolon",
      bubbles: true,
      cancelable: true,
    },
  },
  {
    command: "vsc-markdown.toggleHeadingMenu",
    title: "Heading Menu",
    icon: "$(list-ordered)",
    keybinding: "ctrl+h",
    keyEvent: {
      key: "h",
      code: "KeyH",
      ctrlKey: true,
      bubbles: true,
      cancelable: true,
    },
  },
  {
    command: "vsc-markdown.insertBlockquoteAdvanced",
    title: "Insert Blockquote (Advanced)",
    icon: "$(quote)",
    keybinding: "ctrl+shift+;",
    keyEvent: {
      key: ";",
      code: "Semicolon",
      ctrlKey: true,
      shiftKey: true,
      bubbles: true,
      cancelable: true,
    },
  },
  {
    command: "vsc-markdown.toggleLinkInput",
    title: "Toggle Link Input",
    icon: "$(link)",
    keybinding: "alt+enter",
    keyEvent: {
      key: "Enter",
      code: "Enter",
      altKey: true,
      bubbles: true,
      cancelable: true,
    },
  },
  {
    command: "vsc-markdown.toggleCodeBlockInput",
    title: "Toggle Code Block Input",
    icon: "$(code)",
    keybinding: "alt+enter",
    keyEvent: {
      key: "Enter",
      code: "Enter",
      altKey: true,
      bubbles: true,
      cancelable: true,
    },
  },
  {
    command: "vsc-markdown.hideCodeBlockEdit",
    title: "Hide Code Block Edit",
    icon: "$(close)",
    keybinding: "escape",
    keyEvent: {
      key: "Escape",
      code: "Escape",
      bubbles: true,
      cancelable: true,
    },
  },
  {
    command: "vsc-markdown.selectAllCodeBlock",
    title: "Select All Code Block",
    icon: "$(select-all)",
    keybinding: "ctrl+a",
    keyEvent: {
      key: "a",
      code: "KeyA",
      ctrlKey: true,
      bubbles: true,
      cancelable: true,
    },
  },
  {
    command: "vsc-markdown.indentListAdvanced",
    title: "Indent List (Advanced)",
    icon: "$(indent)",
    keybinding: "ctrl+shift+i",
    keyEvent: {
      key: "i",
      code: "KeyI",
      ctrlKey: true,
      shiftKey: true,
      bubbles: true,
      cancelable: true,
    },
  },
  {
    command: "vsc-markdown.unindentListAdvanced",
    title: "Unindent List (Advanced)",
    icon: "$(outdent)",
    keybinding: "ctrl+shift+o",
    keyEvent: {
      key: "o",
      code: "KeyO",
      ctrlKey: true,
      shiftKey: true,
      bubbles: true,
      cancelable: true,
    },
  },
  {
    command: "vsc-markdown.tableMoveCaretToInput",
    title: "Table: Move Caret to Input",
    icon: "$(arrow-left)",
    keybinding: "alt+enter",
    keyEvent: {
      key: "Enter",
      code: "Enter",
      altKey: true,
      bubbles: true,
      cancelable: true,
    },
  },
  {
    command: "vsc-markdown.tableMoveCaretPrevious",
    title: "Table: Move Caret to Previous Cell",
    icon: "$(arrow-left)",
    keybinding: "shift+tab",
    keyEvent: {
      key: "Tab",
      code: "Tab",
      shiftKey: true,
      bubbles: true,
      cancelable: true,
    },
  },
  {
    command: "vsc-markdown.tableMoveCaretNext",
    title: "Table: Move Caret to Next Cell",
    icon: "$(arrow-right)",
    keybinding: "tab",
    keyEvent: {
      key: "Tab",
      code: "Tab",
      bubbles: true,
      cancelable: true,
    },
  },
  {
    command: "vsc-markdown.insertH6",
    title: "Insert H6 Heading",
    icon: "$(symbol-text)",
    text: "H6",
    keybinding: "ctrl+alt+6",
    keyEvent: {
      key: "6",
      code: "Digit6",
      ctrlKey: true,
      altKey: true,
      bubbles: true,
      cancelable: true,
    },
  },
  {
    command: "vsc-markdown.atUser",
    title: "At User",
    icon: "$(mention)",
    keybinding: "@",
    keyEvent: {
      key: "@",
      code: "Digit2",
      shiftKey: true,
      bubbles: true,
      cancelable: true,
    },
  },
  {
    command: "vsc-markdown.removeMistyped",
    title: "Remove Mistyped",
    icon: "$(undo)",
    keybinding: "backspace",
    keyEvent: {
      key: "Backspace",
      code: "Backspace",
      bubbles: true,
      cancelable: true,
    },
  },
];
