export const Hotkeys = [
  {
    command: "vsc-markdown.insertH1",
    title: "Insert H1 Heading",
    icon: "$(symbol-text)",
    text: "H1",
    keyEvent: {
      key: "1",
      code: "Digit1",
      ctrlKey: true,
      altKey: true,
      bubbles: true,
      cancelable: true,
    },
  },
  {
    command: "vsc-markdown.insertH2",
    title: "Insert H2 Heading",
    icon: "$(symbol-text)",
    text: "H2",
    keyEvent: {
      key: "2",
      code: "Digit2",
      ctrlKey: true,
      altKey: true,
      bubbles: true,
      cancelable: true,
    },
  },
  {
    command: "vsc-markdown.insertH3",
    title: "Insert H3 Heading",
    icon: "$(symbol-text)",
    text: "H3",
    keyEvent: {
      key: "3",
      code: "Digit3",
      ctrlKey: true,
      altKey: true,
      bubbles: true,
      cancelable: true,
    },
  },
  {
    command: "vsc-markdown.insertH4",
    title: "Insert H4 Heading",
    icon: "$(symbol-text)",
    text: "H4",
    keyEvent: {
      key: "4",
      code: "Digit4",
      ctrlKey: true,
      altKey: true,
      bubbles: true,
      cancelable: true,
    },
  },
  {
    command: "vsc-markdown.insertH5",
    title: "Insert H5 Heading",
    icon: "$(symbol-text)",
    text: "H5",
    keyEvent: {
      key: "5",
      code: "Digit5",
      ctrlKey: true,
      altKey: true,
      bubbles: true,
      cancelable: true,
    },
  },
  {
    command: "vsc-markdown.insertBold",
    title: "Insert Bold Text",
    icon: "$(bold)",
    keyEvent: {
      key: "b",
      code: "KeyB",
      ctrlKey: true,
      bubbles: true,
      cancelable: true,
    },
  },
  {
    command: "vsc-markdown.insertItalic",
    title: "Insert Italic Text",
    icon: "$(italic)",
    keyEvent: {
      key: "i",
      code: "KeyI",
      ctrlKey: true,
      bubbles: true,
      cancelable: true,
    },
  },
  {
    command: "vsc-markdown.insertList",
    title: "Insert Unordered List",
    icon: "$(list-unordered)",
    keyEvent: {
      key: "l",
      code: "KeyL",
      ctrlKey: true,
      bubbles: true,
      cancelable: true,
    },
  },
  {
    command: "vsc-markdown.insertOrderedList",
    title: "Insert Ordered List",
    icon: "$(list-ordered)",
    keyEvent: {
      key: "o",
      code: "KeyO",
      ctrlKey: true,
      bubbles: true,
      cancelable: true,
    },
  },
  {
    command: "vsc-markdown.insertLink",
    title: "Insert Link",
    icon: "$(link)",
    keyEvent: {
      key: "k",
      code: "KeyK",
      ctrlKey: true,
      bubbles: true,
      cancelable: true,
    },
  },
  {
    command: "vsc-markdown.insertImage",
    title: "Insert Image",
    icon: "$(file-media)",
  },
  {
    command: "vsc-markdown.insertCodeBlock",
    title: "Insert Code Block",
    icon: "$(code)",
    keyEvent: {
      key: "u",
      code: "KeyU",
      ctrlKey: true,
      bubbles: true,
      cancelable: true,
    },
  },
  {
    command: "vsc-markdown.insertInlineCode",
    title: "Insert Inline Code",
    icon: "$(symbol-string)",
    keyEvent: {
      key: "g",
      code: "KeyG",
      ctrlKey: true,
      bubbles: true,
      cancelable: true,
    },
  },
  {
    command: "vsc-markdown.insertBlockquote",
    title: "Insert Blockquote",
    icon: "$(quote)",
    keyEvent: {
      key: ";",
      code: "Semicolon",
      ctrlKey: true,
      bubbles: true,
      cancelable: true,
    },
  },
  {
    command: "vsc-markdown.insertTable",
    title: "Insert Table",
    icon: "$(table)",
    keyEvent: {
      key: "m",
      code: "KeyM",
      ctrlKey: true,
      bubbles: true,
      cancelable: true,
    },
  },
  {
    command: "vsc-markdown.insertStrikethrough",
    title: "Insert Strikethrough",
    icon: "$(strikethrough)",
    keyEvent: {
      key: "s",
      code: "KeyS",
      ctrlKey: true,
      bubbles: true,
      cancelable: true,
    },
  },
  {
    command: "vsc-markdown.insertEmptyBlock",
    title: "Insert Empty Block",
    icon: "$(add)",
  },
];
